### ISSUE TITLE
B站视频进度条bug

### ISSUE THREAD

**Issue by kris-ho** [honwhy/words-100-helper#1]
B站视频进度条，鼠标拖动进度条，拖动不能定位到指定位置

**Comment by kris-ho** [comment]
![Uploading PixPin_2024-05-09_21-30-57.gif…]()

**Comment by honwhy** [comment]
感谢反馈，问题已修复
1、提前获取修复版本需要手动安装，请从release页面获取安装包
2、更新版本已提交应用市场，等待审批通过
